# Generated by Django 4.2.21 on 2025-05-08 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(default='—', max_length=100)),
                ('workplace', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('contacts', models.TextField()),
                ('motivation_letter', models.TextField()),
                ('social_networks', models.CharField(default='No social networks', max_length=255)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
