# Generated by Django 4.2.21 on 2025-05-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('full_text', models.TextField(blank=True, null=True, verbose_name='Полное описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('youtube_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
