# Generated by Django 4.2.21 on 2025-05-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('courses', 'Курсы и вебинары'), ('video', 'Видео с YouTube'), ('event', 'События')], default='event', max_length=20),
        ),
    ]
