# Generated by Django 4.2.20 on 2025-05-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('workplace', models.CharField(max_length=200, verbose_name='Место работы')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('contacts', models.TextField(verbose_name='Контакты')),
                ('motivation_letter', models.TextField(verbose_name='Мотивационное письмо')),
                ('social_networks', models.URLField(blank=True, null=True, verbose_name='Социальные сети')),
                ('resume', models.FileField(upload_to='resumes/', verbose_name='Загрузить резюме')),
            ],
        ),
    ]
