# Generated by Django 4.2.20 on 2025-05-06 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationmember',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='associationmember',
            name='last_name',
        ),
        migrations.AddField(
            model_name='associationmember',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='associationmember',
            name='contacts',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='associationmember',
            name='motivation_letter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='associationmember',
            name='patronymic',
            field=models.CharField(default='—', max_length=100),
        ),
        migrations.AlterField(
            model_name='associationmember',
            name='position',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='associationmember',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='associationmember',
            name='social_networks',
            field=models.CharField(default='No social networks', max_length=255),
        ),
        migrations.AlterField(
            model_name='associationmember',
            name='workplace',
            field=models.CharField(max_length=255),
        ),
    ]
