# Generated by Django 5.2 on 2025-05-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='full_text',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
    ]
