# Generated by Django 5.2 on 2025-05-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_news_full_text_alter_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationmember',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
