# Generated by Django 4.2.21 on 2025-05-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_associationmember_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationmember',
            name='user',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='AssociationMember',
        ),
    ]
