# Generated by Django 4.2.10 on 2025-05-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0006_remove_associationmember_user_delete_news_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('about', models.TextField(verbose_name='О себе')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специализация')),
                ('cases', models.TextField(blank=True, verbose_name='Кейсы')),
                ('is_member', models.BooleanField(default=False, verbose_name='Участник Ассоциации')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('social_links', models.TextField(blank=True, verbose_name='Социальные сети')),
            ],
        ),
    ]
