# Generated by Django 4.2.10 on 2025-05-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_coursecategory_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
