# Generated by Django 4.2.21 on 2025-05-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_coursecategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='full_description_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='full_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='title_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
