# Generated by Django 4.2.21 on 2025-05-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_course_full_description_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='about_kk',
            field=models.TextField(null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='cases_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Кейсы'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='cases_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Кейсы'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='category_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='category_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='position_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='position_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='specialization_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='specialization_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Специализация'),
        ),
    ]
