# Generated by Django 5.2.1 on 2025-05-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_specialist_about_kk_specialist_about_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='awards',
            field=models.TextField(blank=True, verbose_name='Награды'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Стаж в PR/медиа'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='job_description',
            field=models.TextField(blank=True, verbose_name='О компании'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='job_region',
            field=models.CharField(blank=True, max_length=255, verbose_name='Регион работы'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=50, verbose_name='Статус модерации'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='motivation',
            field=models.TextField(blank=True, verbose_name='Мотивация'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='phone',
            field=models.CharField(default='', max_length=50, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialist',
            name='publications',
            field=models.TextField(blank=True, verbose_name='Публикации'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='recommender',
            field=models.TextField(blank=True, verbose_name='Рекомендатель'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='skills',
            field=models.TextField(blank=True, verbose_name='Навыки и сертификаты'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='workplace',
            field=models.CharField(default='', max_length=255, verbose_name='Место работы'),
            preserve_default=False,
        ),
    ]
