# Generated by Django 4.2.21 on 2025-08-14 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_update_specialist_model'),
        ('myapp', '0013_specialist_awards_specialist_email_and_more'),
    ]

    operations = [
    ]
