# Generated by Django 4.2.21 on 2025-08-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_merge_20250814_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Специалист', 'verbose_name_plural': 'Специалисты'},
        ),
        migrations.AlterField(
            model_name='specialist',
            name='about',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='about_kk',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='category_kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='category_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Стаж в PR/медиа'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='position_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='position_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='specialization_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='specialization_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='workplace',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место работы'),
        ),
    ]
