# Generated by Django 4.2.21 on 2025-08-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_specialist_options_alter_specialist_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='consent_rules',
            field=models.BooleanField(default=False, verbose_name='Согласие с правилами Ассоциации'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='job_description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='О компании'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='job_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='О компании'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='motivation_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Мотивация'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='motivation_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Мотивация'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='professional_description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание профессиональной деятельности'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='professional_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание профессиональной деятельности'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='skills_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Навыки и сертификаты'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='skills_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Навыки и сертификаты'),
        ),
    ]
