# Generated by Django 4.2.21 on 2025-08-14 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_fix_specialist_photo'),
        ('myapp', '0016_specialist_consent_rules_and_more'),
    ]

    operations = [
    ]
