# Generated by Django 4.2.21 on 2025-09-03 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_merge_20250814_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='job_description_kk',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='job_description_ru',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='motivation_kk',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='motivation_ru',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='professional_description_kk',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='professional_description_ru',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='skills_kk',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='skills_ru',
        ),
    ]
