# Generated by Django 4.2.21 on 2025-08-14 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_add_missing_fields_to_specialist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='job_description_kk',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='job_description_ru',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='motivation_kk',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='motivation_ru',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='professional_description_kk',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='professional_description_ru',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='skills_kk',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='skills_ru',
        ),
    ]
