# Generated by Django 4.2.21 on 2025-08-14 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_safe_add_fields_to_specialist'),
        ('myapp', '0019_remove_specialist_job_description_kk_and_more'),
    ]

    operations = [
    ]
