# Generated by Django 4.2.21 on 2025-08-14 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_merge_20250814_0426'),
    ]

    operations = [
    ]
